name: Deploy .NET 8 app to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - "Program.cs"
      - "az104-appservice-lab.csproj"

  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_VERSION: "8.x"
  AZURE_WEBAPP_NAME: "az104-josh-webapp"

jobs:
  build:
    name: Build application
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build application
        run: dotnet build --configuration Release

      - name: Publish application
        run: dotnet publish --configuration Release --no-build --output ./publish

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./publish

  deploy:
    name: Deploy to Azure App Service
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ./publish

      - name: Deploy application
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "Production"
          package: ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_01B6E8781692473DB086E23F4973D3AB }}
